<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2018-11-29T23:38:43</date>
  <millis>1543520323785</millis>
  <sequence>16</sequence>
  <logger>Server.JoinedClient</logger>
  <level>FINE</level>
  <class>Server.JoinedClient</class>
  <method>run</method>
  <thread>13</thread>
  <message>ID 3 подключен к серверу.</message>
</record>
<record>
  <date>2018-11-29T23:38:43</date>
  <millis>1543520323785</millis>
  <sequence>17</sequence>
  <logger>Server.JoinedClient</logger>
  <level>FINE</level>
  <class>Server.JoinedClient</class>
  <method>run</method>
  <thread>13</thread>
  <message>ID 3 ожидание запросов.</message>
</record>
<record>
  <date>2018-11-29T23:38:44</date>
  <millis>1543520324764</millis>
  <sequence>18</sequence>
  <logger>Server.JoinedClient</logger>
  <level>FINE</level>
  <class>Server.JoinedClient</class>
  <method>run</method>
  <thread>12</thread>
  <message>ID 2 произошла ошибка на стороне клиента</message>
</record>
<record>
  <date>2018-11-29T23:38:50</date>
  <millis>1543520330352</millis>
  <sequence>19</sequence>
  <logger>Server.JoinedClient</logger>
  <level>FINE</level>
  <class>Server.JoinedClient</class>
  <method>run</method>
  <thread>13</thread>
  <message>ID 3 передал на сервер:f:f</message>
</record>
<record>
  <date>2018-11-29T23:38:50</date>
  <millis>1543520330359</millis>
  <sequence>20</sequence>
  <logger>Server.JoinedClient</logger>
  <level>INFO</level>
  <class>Server.JoinedClient</class>
  <method>getConnect</method>
  <thread>13</thread>
  <message>Сервер подключился к БД</message>
</record>
<record>
  <date>2018-11-29T23:38:50</date>
  <millis>1543520330360</millis>
  <sequence>21</sequence>
  <logger>Server.JoinedClient</logger>
  <level>FINEST</level>
  <class>Server.JoinedClient</class>
  <method>autorize</method>
  <thread>13</thread>
  <message>ID 3 делает запрос на авторизацию log=f, pass=f</message>
</record>
<record>
  <date>2018-11-29T23:38:50</date>
  <millis>1543520330361</millis>
  <sequence>22</sequence>
  <logger>Server.JoinedClient</logger>
  <level>FINE</level>
  <class>Server.JoinedClient</class>
  <method>run</method>
  <thread>13</thread>
  <message>ID 3 авторизовался на сервере</message>
</record>
<record>
  <date>2018-11-29T23:39:28</date>
  <millis>1543520368124</millis>
  <sequence>23</sequence>
  <logger>Server.JoinedClient</logger>
  <level>FINE</level>
  <class>Server.JoinedClient</class>
  <method>run</method>
  <thread>13</thread>
  <message>ID 3 произошла ошибка на стороне клиента</message>
</record>
</log>
